import React, { useEffect, useState } from 'react';
import * as api from '@/lib/api';
import './agentStudio.css';

export default function AgentDataPanel({ agentName }) {
  const [outputs, setOutputs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let active = true;
    const fetchOutputs = async () => {
      if (!agentName) return;
      setLoading(true);
      setError(null);
      try {
        const data = await api.getAgentOutputs(agentName, 50);
        if (active && Array.isArray(data)) {
          setOutputs(data);
        }
      } catch (err) {
        if (active) setError(err.message || 'Failed to fetch agent outputs');
      } finally {
        if (active) setLoading(false);
      }
    };

    fetchOutputs();

    // Optionally poll every 10 seconds if we expect new outputs
    const interval = setInterval(fetchOutputs, 10000);

    return () => {
      active = false;
      clearInterval(interval);
    };
  }, [agentName]);

  if (loading && outputs.length === 0) {
    return (
      <div className="agent-studio__empty">
        <span className="spinner" style={{ width: 16, height: 16, marginRight: 8 }} />
        Fetching processed data...
      </div>
    );
  }

  if (error) {
    return (
      <div className="agent-studio__empty" style={{ color: 'var(--sell)' }}>
        ⚠️ {error}
      </div>
    );
  }

  if (outputs.length === 0) {
    return (
      <div className="agent-studio__empty">
        <div style={{ fontSize: '2rem', marginBottom: '1rem' }}>📭</div>
        <div>No processed data or outputs found for {agentName}.</div>
      </div>
    );
  }

  return (
    <div className="agent-studio__data-panel" style={{ height: '100%', overflowY: 'auto', padding: 'var(--space-md)' }}>
      <div style={{ marginBottom: 'var(--space-md)' }}>
        <h3 style={{ margin: 0, fontSize: '1.1rem', color: 'var(--text-primary)' }}>Processed Outputs</h3>
        <p style={{ margin: '4px 0 0 0', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          Recent analysis results and structured data generated by <strong>{agentName}</strong>.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
        {outputs.map((out) => (
          <div key={out.id} className="agent-studio__data-card" style={{ background: 'var(--background-secondary)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', padding: 'var(--space-md)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 'var(--space-sm)' }}>
              <strong style={{ color: 'var(--text-primary)' }}>
                {out.ticker}
              </strong>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                {new Date(out.created_at).toLocaleString()}
              </span>
            </div>
            
            {out.confidence !== null && (
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 'var(--space-sm)' }}>
                Confidence: {(out.confidence * 100).toFixed(1)}%
              </div>
            )}
            
            <div style={{ background: 'var(--bg-card)', padding: 'var(--space-sm)', borderRadius: 'var(--radius-sm)', overflowX: 'auto', fontSize: '0.8rem' }}>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-all', color: 'var(--text-secondary)' }}>
                {JSON.stringify(out.result_json, null, 2)}
              </pre>
            </div>
            
            <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: '8px', textAlign: 'right' }}>
              Cycle ID: {out.cycle_id}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
